version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - 8123:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - homeassistant:/config
      - ./custom_components:/config/custom_components

volumes:
  homeassistant:
