name: "Ollama"
description: "The easiest way to get up and running with large language models locally"
version: "0.1.32"
slug: "ollama"
init: false
arch:
  - aarch64
  - amd64
url: https://ollama.com
ports:
  11434/tcp: 11434
image: docker.io/ollama/ollama
ingress: true
ingress_port: 11434
map:
  - config:rw
environment:
  OLLAMA_MODELS: "/config/ollama"
