name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  main:
    name: lint and create issues
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 2

      - uses: alstr/todo-to-issue-action@v4
        with:
          AUTO_ASSIGN: true

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: yarn install

      - run: yarn lint
